### ISSUE TITLE
CHATPROXY引发账号泄露的风险？

### ISSUE THREAD

**Issue by muyiai** [xyhelper/chatgpt-mirror-server#5]
CHATPROXY是作者搭建的API转发代理么，这里存在一个风险，是不是我们部署后，所有的账号相关的数据都会通过这个代理转发，那么账号是不是就有暴露的风险？

**Comment by gcslaoli** [comment]
存在，不放心的可以部署蟑螂

**Comment by homeofmny** [comment]
> 存在，不放心的可以部署蟑螂

您好，请问一下蟑螂是指什么呢？不太明白求解惑，谢谢！

**Comment by gcslaoli** [comment]
> > 存在，不放心的可以部署蟑螂
> 
> 您好，请问一下蟑螂是指什么呢？不太明白求解惑，谢谢！

https://github.com/cockroachai/cockroachai
