### ISSUE TITLE
get session error "Tm90IEZvdW5k"

### ISSUE THREAD

**Issue by lrxcy** [xyhelper/chatgpt-mirror-server#6]
您好可以帮忙确认一下这个获取session错误如何修复的问题吗，非常感谢

2023-11-09 11:19:34.032 [ERRO] {d79733d238d69517a931e0446220f5c5} ChatgptSessionService.ModifyAfter get session error "Tm90IEZvdW5k"
Stack:
1.  chatgpt-mirror-server/modules/chatgpt/service.(*ChatgptSessionService).ModifyAfter
    /workspaces/chatgpt-mirror-server/modules/chatgpt/service/chatgpt_session.go:55
2.  github.com/cool-team-official/cool-admin-go/cool.(*Controller).Update
    /go/pkg/mod/github.com/cool-team-official/cool-admin-go/cool@v1.5.2/controller.go:117
3.  github.com/cool-team-official/cool-admin-go/cool.MiddlewareHandlerResponse
    /go/pkg/mod/github.com/cool-team-official/cool-admin-go/cool@v1.5.2/middleware_handler_response.go:25
4.  github.com/cool-team-official/cool-admin-go/modules/base/middleware.AutoI18n
    /go/pkg/mod/github.com/cool-team-official/cool-admin-go/modules/base@v1.5.2/middleware/i18n.go:16
5.  github.com/cool-team-official/cool-admin-go/modules/base/middleware.BaseLog
    /go/pkg/mod/github.com/cool-team-official/cool-admin-go/modules/base@v1.5.2/middleware/log.go:15
6.  github.com/cool-team-official/cool-admin-go/modules/base/middleware.BaseAuthorityMiddleware
    /go/pkg/mod/github.com/cool-team-official/cool-admin-go/modules/base@v1.5.2/middleware/authority.go:80

![image](https://github.com/xyhelper/chatgpt-mirror-server/assets/34975746/eb9ec573-a772-4019-9501-66443d2e59f6)

**Comment by gcslaoli** [comment]
临时网络错误，重新获取一下

**Comment by lrxcy** [comment]
哎，我已经换了三台服务器了，都是不同的网络，也有在使用openapi服务的设备，都是一样的错误。。。这个是redis里面需要先预设一个session吗
